package imgchofer;
public void inicializar(){
    Pregunta p1= agregarPregunta("Sus ruedas deben estar mirando hacia adelante, a menos que?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Esté esperando a dar la vuelta a la izquierda en un semáforo.",Tipo_Respuesta.INCORRECTA,p1);
    agregarRespuesta(null,"Esté estacionado en una colina o en una acceso inclinado",Tipo_Respuesta.CORRECTA,p1);
    agregarRespuesta(null,"Esté estacionado a un costado a nivel de la calle donde no hay acera",Tipo_Respuesta.INCORRECTA,p1);
    Pregunta p2= agregarPregunta("Cuando maneje en niebla, lluvia o nieve, debe usar:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Sus luces bajas",Tipo_Respuesta.CORRECTA,p2);
    agregarRespuesta(null,"Sus luces altas",Tipo_Respuesta.INCORRECTA,p2);
    agregarRespuesta(null,"Solo luces de manejo",Tipo_Respuesta.INCORRECTA,p2);
    Pregunta p3= agregarPregunta("Cuando ve esta señal, significa que usted?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Se está acercando a las vías de tren. Prepárese para detenerse",Tipo_Respuesta.CORRECTA,p3);
    agregarRespuesta(null,"Siempre debe tenerse en el siguiente cruce de las vías del tren.",Tipo_Respuesta.INCORRECTA,p3);
    agregarRespuesta(null,"Debe detenerse y esperar a una señal antes de cruzar las vías del tren",Tipo_Respuesta.INCORRECTA,p3);
    Pregunta p4= agregarPregunta("Si un camión o un autobús necesita girar a la derecha y usted también está dando vuelta a la derecha?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Dé vuelta rápidamente a la derecha antes del camión o autobús",Tipo_Respuesta.INCORRECTA,p4);
    agregarRespuesta(null,"Espere hasta que el camión o el autobús dé vuelta antes de dar vuelta usted",Tipo_Respuesta.CORRECTA,p4);
    agregarRespuesta(null,"Pase entre el camión y el autobús y el bordillo",Tipo_Respuesta.INCORRECTA,p4);
    Pregunta p5= agregarPregunta("Debe incrementar la distancia entre su vehículo y el vehículo delante de usted cuando?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Siga a un vehículo pequeño de pasajeros",Tipo_Respuesta.INCORRECTA,p5);
    agregarRespuesta(null,"Lo esté siguiendo de cerca otro vehículo",Tipo_Respuesta.CORRECTA,p5);
    agregarRespuesta(null,"Vaya a menos velocidad que el límite máximo",Tipo_Respuesta.INCORRECTA,p5);
    Pregunta p6= agregarPregunta("Cuando maneja en nieve o condiciones heladas?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Es seguro usar el regulador de velocidad",Tipo_Respuesta.INCORRECTA,p6);
    agregarRespuesta(null,"Haga cambios de velocidad y de dirección de forma más gradual",Tipo_Respuesta.CORRECT,p6);
    agregarRespuesta(null,"Maneje como lo haría en condiciones normales.",Tipo_Respuesta.INCORRECTA,p6);
    Pregunta p7= agregarPregunta("7. Una línea amarilla discontinua central indica:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Que adelantar no está permitido",Tipo_Respuesta.INCORRECTA,p7);
    agregarRespuesta(null,"Adelantar está permitido en la derecha cuando el camino está despejado",Tipo_Respuesta.INCORRECTA,p7);
    agregarRespuesta(null,"Adelantar está permitido por la izquierda cuando el camino de adelante está despejado",Tipo_Respuesta.CORRECTA,p7);
    Pregunta p8= agregarPregunta("¿Cuál de las siguientes afirmaciones aplica al cambiar de carril?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Solo necesita girarse y mirar sobre su hombro derecho para cambiar de carril a la derecha o a la izquierda",Tipo_Respuesta.INCORRECTA,p8);
    agregarRespuesta(null,"Debe mirar sobre su hombro derecho para cambiar al carril derecho y sobre el hombro izquierdo para cambiar al carril izquierdo",Tipo_Respuesta.CORRECTA,p8);
    agregarRespuesta(null,"Los vehículos con dos espejos retrovisores externos no tienen puntos ciegos",Tipo_Respuesta.INCORRECTA,p8);
    Pregunta p9= agregarPregunta("¿Cuál de las siguientes acciones le ayudará a evitar que le choquen por detrás?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Entrar a otro carril.",Tipo_Respuesta.CORRECTA,p9);
    agregarRespuesta(null,"Disminuir la distancia de seguimiento entre su vehículo y otro.",Tipo_Respuesta.CORRECTA,p9);
    agregarRespuesta(null,"Cambiar frecuentemente de carril.",Tipo_Respuesta.INCORRECTA,p9);
    Pregunta p10= agregarPregunta("Si se acerca a un semáforo con una señal roja y un oficial de policía le indica que atraviese la intersección sin detenerse, usted debe:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Detenerse hasta que la luz se ponga verde.",Tipo_Respuesta.INCORRECTA,p10);
    agregarRespuesta(null,"Pasar por la intersección sin detenerse.",Tipo_Respuesta.CORRECTA,p10);
    agregarRespuesta(null,"Hacer una parada completa antes de continuar con precaución.",Tipo_Respuesta.CORRECTA,p10);
    Pregunta p11= agregarPregunta("¿Cuál de los siguientes factores afectan la absorción individual de alcohol?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"El peso.",Tipo_Respuesta.CORRECTA,p11);
    agregarRespuesta(null,"La altura.",Tipo_Respuesta.INCORRECTA,p11);
    agregarRespuesta(null,"La raza.",Tipo_Respuesta.INCORRECTA,p11);
    Pregunta p12= agregarPregunta("Esta señal blanca significa que usted:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Debe bajar la velocidad y moverse hacia el carril derecho.",Tipo_Respuesta.INCORRECTA,p12);
    agregarRespuesta(null,"Debe quedarse en el carril derecho si está manejando más lento que el resto del tráfico.",Tipo_Respuesta.CORRECTO,p12);
    agregarRespuesta(null,"El tráfico lento debe salir por la derecha.",Tipo_Respuesta.INCORRECTA,p12);
    Pregunta p13= agregarPregunta("Una señal naranja y roja con esta forma en un vehículo siempre significa:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Una señal naranja y roja con esta forma en un vehículo siempre significa:",Tipo_Respuesta.INCORRECTA,p13);
    agregarRespuesta(null,"Un vehículo que anda lentamente.",Tipo_Respuesta.CORRECTO,p13);
    agregarRespuesta(null,"Cuneta en obras más adelante.",Tipo_Respuesta.INCORRECTA,p13);
    Pregunta p14= agregarPregunta("La fatiga incrementa la probabilidad de:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Saltarse una salida.",Tipo_Respuesta.INCORRECTA,p14);
    agregarRespuesta(null,"Llegar tarde a una cita",Tipo_Respuesta.INCORRECTA,p14);
    agregarRespuesta(null,"Quedarse dormido tras el volante y chocar",Tipo_Respuesta.CORRECTO,p14);
    Pregunta p15= agregarPregunta("Esta señal significa:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"El vehículo a la derecha va primero.",Tipo_Respuesta.INCORRECTA,p15);
    agregarRespuesta(null,"Usted tiene el derecho de paso.",Tipo_Respuesta.INCORRECTA,p15);
    agregarRespuesta(null,"Deje que el tráfico que está cruzando vaya primero.",Tipo_Respuesta.CORRECTO,p15);
    Pregunta p16= agregarPregunta("¿Cuál de los siguientes obstruye el flujo regular del tráfico?",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Bajar la velocidad para ver un choque",Tipo_Respuesta.CORRECTO,p16);
    agregarRespuesta(null,"Evitar cambios innecesarios de carril",Tipo_Respuesta.INCORRECTA,p16);
    agregarRespuesta(null,"Usar el transporte público en lugar de su vehículo",Tipo_Respuesta.INCORRECTA,p16);
    Pregunta p17= agregarPregunta("Usted quiere dar un giro a la derecha en la próxima intersección. Usted debe bajar la velocidad y:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Moverse hacia el lado izquierdo de su carril.",Tipo_Respuesta.INCORRECTA,p17);
    agregarRespuesta(null,"Evitar manejar sobre el carril de bicicletas.",Tipo_Respuesta.INCORRECTA,p17);
    agregarRespuesta(null,"Poner las luces direccionales desde 100 pies antes de dar el giro.",Tipo_Respuesta.CORRECTO,p17);
    Pregunta p18= agregarPregunta("En zonas en obra, usted debe:",Tipo_Pregunta.TEORICA);
    agregarRespuesta(null,"Acelerar para pasar lo más rápido posible",Tipo_Respuesta.INCORRECTA,p18);
    agregarRespuesta(null,"Reducir su velocidad y estar preparado para detenerse repentinamente.",Tipo_Respuesta.INCORRECTA,p18);
    agregarRespuesta(null,"Mantener su velocidad mientras avanza por la zona.",Tipo_Respuesta.INCORRECTA,p18);
    Pregunta p19= agregarPregunta("Qué señal indica, Escolares en la vía?",Tipo_Pregunta.COGNITIVA);
    agregarRespuesta("sobrecebra.jpeg",null,Tipo_Respuesta.INCORRECTA,p19);
    agregarRespuesta("peatones.jpeg",null,Tipo_Respuesta.INCORRECTO,p19);
    agregarRespuesta("escolares",null,Tipo_Respuesta.CORRECTO,p19);
    Pregunta p20= agregarPregunta("Cual es la luz roja",Tipo_Pregunta.COGNITIVA);
    agregarRespuesta("red.png",null,Tipo_Respuesta.CORRECTO,p20);
    agregarRespuesta("yellow.png",null,Tipo_Respuesta.INCORRECTA,p20);
    agregarRespuesta("green.png",null,Tipo_Respuesta.INCORRECTA,p20);
    Pregunta p21= agregarPregunta("Cual es la luz verde",Tipo_Pregunta.COGNITIVA);
    agregarRespuesta("red.png",null,Tipo_Respuesta.INCORRECTA,p21);
    agregarRespuesta("yellow.png",null,Tipo_Respuesta.INCORRECTA,p21);
    agregarRespuesta("green.png",null,Tipo_Respuesta.CORRECTO,p21);
    Pregunta p22= agregarPregunta("Cual es la luz amarilla",Tipo_Pregunta.COGNITIVA);
    agregarRespuesta("red.png",null,Tipo_Respuesta.INCORRECTA,p22);
    agregarRespuesta("yellow.png",null,Tipo_Respuesta.CORRECTO,p22);
    agregarRespuesta("green.png",null,Tipo_Respuesta.INCORRECTA,p22);
}